name: Tests

on:
  push:
    paths:
      - contracts/**/*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        working-directory: contracts
        run: forge fmt --check

      - name: Install dependencies
        working-directory: contracts
        run: forge install

      - name: Check contract sizes
        working-directory: contracts
        run: forge build --sizes

      - name: Run tests
        working-directory: contracts
        run: forge test
        env:
          # Only fuzz intensely if we're running this action on a push to main or for a PR going into main:
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'intense' }}
          MAINET_RPC_URL: ${{ secrets.MAINET_RPC_URL }}